graphql:
  packages:
    - "io.dflowers.user"
oauth2:
  google:
    redirect_uri: ${GOOGLE_REDIRECT_URI}
    token_url: https://oauth2.googleapis.com/token
    client_id: ${GOOGLE_CLIENT_ID}
    secret_id: ${GOOGLE_SECRET_ID}