spring:
  profiles:
    active: local
  application:
    name: user

grpc:
  server:
    port: 6565

management:
  tracing:
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
