package io.dflowers.user.dto

enum class ErrorCode {
    NOT_FOUND,
    UNNECESSARY_PURCHASE,
    NOT_ENOUGH_USER_COIN,
    NOT_ADULT_VERIFIED,
    INVALID_TOKEN,
    WRONG_CREDENTIALS,
    ALREADY_REGISTERED,
}
